# docker run --name saloonly-pg -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=saloonlydocker -e POSTGRESQL_DATABASE=apisaloonly -p 5432:5432  bitnami/postgresql

version: "3"

services:
  saloonly-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=saloonlydocker
      - POSTGRESQL_DATABASE=apisaloonly
